### PR TITLE
Specify driver connectivity to be L2

### PR DESCRIPTION
**Pull request by tzumainn**
This property is needed to enable certain Neutron functionality.

### CODE REVIEW

**Comment by tzumainn** [comment]
@naved001 @hakasapl could you take a quick look at this? Thanks!

**Review by naved001 — COMMENTED** [review]
Is this what enables us to configure the switchports without having to create a neutron subnet? If so, I don't understand how or why this change enables that. 

Also the commit message could be improved to say what the "certain Neutron functionality" it enables.

**Comment by tzumainn** [comment]
Fair! I've updated the commit description to be more specific.

The Neutron code that checks this is https://opendev.org/openstack/neutron/blame/commit/c21a9169c69ad612e9d468e943ae822d64c86b61/neutron/plugins/ml2/managers.py#L1062-L1073

**Review by naved001 — APPROVED** [review]

**Comment by tzumainn** [comment]
@DanNiESh could you take a quick look at this one? Thanks!

**Review by DanNiESh — APPROVED** [review]

**Comment by tzumainn** [comment]
@naved001 is this something you can merge? I don't seem to have permissions

**Pull request merged**
